### ISSUE TITLE
Expanded action states for balances

### ISSUE THREAD

**Issue by jinchung** [balance-io/balance-wallet#123]
Transactions: show on Etherscan
Balances: send, view on CoinMarketCap? 
Collectibles: view on OpenSea

**Comment by tmlee** [comment]
If you are looking for market and additional data regarding cryptocurrencies, may I suggest checking out our open public API too for consideration at coingecko.com/api

Updates directly from token teams (https://www.coingecko.com/en/beam) can be a good addition too and available as an api at https://www.coingecko.com/api/docs/v3#/coins/get_coins__id__status_updates

Happy to answer any questions and concerns you may have!
