### ISSUE TITLE
Multiple vibrations when scanning ETH address on normal camera screen

### ISSUE THREAD

**Issue by mirshko** [balance-io/balance-wallet#182]
@jinchung looks like this is related to the fact the camera is still active once the address has been scanned.

![img_3116](https://user-images.githubusercontent.com/8116716/48017369-70157600-e12e-11e8-982f-2ec76a519871.jpg)

the vibrations stop once the QR Code is out of the camera's view.

**Comment by mirshko** [comment]
This behavior is only from the primary camera view. From "Send" screen this works as intended.

**Comment by jinchung** [comment]
Fixed now
