### ISSUE TITLE
📲Setting up fastlane and testflight > testing flow

### ISSUE THREAD

**Issue by jinchung** [balance-io/balance-wallet#20]

**Comment by ricburton** [comment]
I have created a `fastlane` branch and I am following the instructions in this blog post:
 https://medium.com/react-native-training/fastlane-for-react-native-ios-android-app-devops-8ca85bee614e

I am currently blocked on our App Store banking agreement. Apple says:

_Note: Banking update in progress, your changes should be reflected within 24 hours.
You will not be able to make any changes until your update completes processing._

The joys of centralised gatekeepers for software. 😂

**Comment by ricburton** [comment]
App is created on iTunes. All legal agreements to ship a piece of software have been signed. Felt weird.

**Comment by ricburton** [comment]
OK great. Running `fastlane` tries to buidl and the project and the errors that are happening now are due to the project itself.

The next blocker is the code signing stuff. Going to pair with @jinchung on this in the other issue.
