### ISSUE TITLE
webConnector.signTypedData(msgParams) crashes the app

### ISSUE THREAD

**Issue by NoahZinsmeister** [balance-io/balance-wallet#249]
After connecting to https://example.walletconnect.org/, clicking 'Sign Test Typed Data' (which under the hood calls `webConnector.signTypedData(msgParams)`) consistently crashes my app (v0.2.1 (3)).

`Send Test Transaction` also times out/causes crashes.

![ezgif-1-70ac3a02666d](https://user-images.githubusercontent.com/3760414/49975455-0c8c1e80-ff0c-11e8-8665-d044ad43ecb1.gif)

![ezgif-1-a19240b6b012](https://user-images.githubusercontent.com/3760414/49975716-18c4ab80-ff0d-11e8-99ab-a8dc67193114.gif)

**Comment by jinchung** [comment]
Thanks @NoahZinsmeister ! 
The typed data will be supported in our next version bump (next week), and the test transaction should be fixed now from the Example Dapp end (it was using "input" instead of the "data" parameter).
