### ISSUE TITLE
🔏Code Signing

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-wallet#28]
This is something that I think we should be very careful about. It is an important section of the fastlane toolchain. 

I trust @jinchung to look at this and get this right:

Match Setup (Code Signing)
https://medium.com/react-native-training/fastlane-for-react-native-ios-android-app-devops-8ca85bee614e

**Comment by ricburton** [comment]
Hey @jinchung,

When you have time, let's go through the [Codesigning Guide](https://codesigning.guide/) together. I trust you to get this right 👍

**Comment by wolffan** [comment]
deffo can help here
