### ISSUE TITLE
📑Support for ERC-712 transaction information

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-wallet#33]
![dfgeh7pvaaasrbz](https://user-images.githubusercontent.com/438160/42547561-ca7d6b34-8490-11e8-8183-dccdf3dfbb5b.jpg)

https://twitter.com/0xproject/status/1006587684234584064?lang=en

https://eips.ethereum.org/EIPS/eip-712

This is really important.

**Comment by jinchung** [comment]
This will be taken care of by another issue for signing typed data
